### ISSUE TITLE
Create to-do list

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/pergel#3]
My aim is to start with very small steps so that everyone can contribute.

Features I would like to have in the structure Nuxt 3 

- [ ] Auth
- [ ] Mobile App
- [ ] Admin Panel
- [ ] Web
- [ ] Api
- [ ] GraphQL
- [ ] Image Upload
- [ ] Stripe - Payment - Even more than that
- [ ] Drizzle + PostgresQL
- [x] Docs Website https://github.com/oku-ui/docs/issues/84
- [ ] ... more

If you have anything you want, please let me know in the comments, maybe it will help me to move forward. I am open to all feedback.I am sure the contributions will increase as the structure slowly emerges. Especially follow pr.

**Comment by erayakgunn** [comment]
Seeing Redis and Kafka would be nice.
