### ISSUE TITLE
List and research to be done

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/pergel#37]
I finally figured out how to make the structure. I wrote it for GraphQL, I'm going to do some tests on my own project today and this week and then I'll open a few more and publish them. Yes, this will be a Nuxt 3 Module and I am coming up with a structure that will make it easier for you to contribute.

I want to see what you want most in the ecosystem.

Which software libraries do you use frequently in Nuxt 3 ? What are your repetitive structures

- [x] graphql-yoga
- [x] graphql codegen
- [x] node-cron
- [x] rabbitmq
- [x] bullmq
- [x] drizzle
- [ ] ...You write one too.

Tell me what you want and we'll try to find a solution.

![image](https://github.com/oku-ui/pergel/assets/38668796/7f230d53-9b0c-48cc-bded-179129cb3eaa)

**Comment by geminigeek** [comment]
Lavinmq

**Comment by Intevel** [comment]
BullMQ

**Comment by productdevbook** [comment]
Most of them are gone now. Drizzle is on its way. After structural improvements and closed testing, I'll make it public.

![image](https://github.com/oku-ui/pergel/assets/38668796/14519636-cc4b-47da-811e-84091e15265b)

**Comment by productdevbook** [comment]
Check example [folders](https://github.com/oku-ui/pergel/tree/main/examples)

**Comment by productdevbook** [comment]
and drizzle, I'm releasing it soon. It's in Maine. I am closing this issua. If you need new modules, you can open an issua, if you can, you can send a pr.
